#19 Add support for nullable reference types - fixing "AmbientStorage.cs(27,50): error CS0305: Using the generic type 'AmbientStorage<TData>' requires 1 type arguments" -> AppVeyor CI does not support  the nameof operator without generic arguments for .net 4.0